# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 10:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('pub_date', models.DateField()),
                ('content', models.TextField()),
                ('image_url', models.TextField()),
            ],
        ),
    ]
